#!/bin/bash
work_dir="`pwd`"
txt_dir="/home/owner/taguchi/data/kikurage_data/"
name=$1
save_path="./$name/datasets"
mkdir $save_path
find ./$name/test_latest/images/ -name "*fake_B*" | xargs -I {} cp {} $save_path/
cd $save_path
for file in *
do number=$(echo "$file" | grep -oE '[0-9]+')
	new_name="IMG_${number}.png"
	mv "$file" "$new_name"
	echo $new_name
done

cd $txt_dir
ls IMG_{1..1235}.txt | xargs -I {} cp {} $work_dir/$save_path

cd $work_dir
