#!/bin/bash
name=$1
work_dir="`pwd`"
save_path="./$name/datasets"
mkdir $save_path
find ./$name/test_latest/images/ -name "*fake_B*" | xargs -I {} cp {} $save_path/

cd $save_path
for file in *
do number=$(echo "$file" | grep -oE '[0-9]+')
	new_name="IMG_${number}.png"
	mv "$file" "$new_name"
	echo $new_name
done
cd $work_dir

find /home/owner/taguchi/RetinaGan/cyclegan/datasets/obj/testA/ -name "*.txt" | xargs -I {} cp {} $save_path/
